export type CabinetReferenceOption = {
  label: string;
  value: string;
};

export const cabinetReferenceSelectOptions: CabinetReferenceOption[] = [
  { label: "AAB - Light Gray", value: "content/cabinets/aab.md" },
  { label: "AAP - Light Grey", value: "content/cabinets/aap.md" },
  { label: "ABB - Blue", value: "content/cabinets/abb.md" },
  { label: "ACB - Espresso Stain", value: "content/cabinets/acb.md" },
  { label: "AEB - Black", value: "content/cabinets/aeb.md" },
  { label: "ALGB - Artisanal Light Gray", value: "content/cabinets/algb.md" },
  { label: "ANM - New Grey Shaker", value: "content/cabinets/anm.md" },
  { label: "AOP - Off White", value: "content/cabinets/aop.md" },
  { label: "ARM - New Grey Shaker", value: "content/cabinets/arm.md" },
  { label: "ATB - Light Brown Stain", value: "content/cabinets/atb.md" },
  { label: "AWB - White", value: "content/cabinets/awb.md" },
  { label: "AXM - Extreme Blue Shaker", value: "content/cabinets/axm.md" },
  { label: "BFK - Light Brown Stain", value: "content/cabinets/bfk.md" },
  { label: "BGK - Gray", value: "content/cabinets/bgk.md" },
  { label: "BMK - Blue", value: "content/cabinets/bmk.md" },
  { label: "BSK - Gray Stain", value: "content/cabinets/bsk.md" },
  { label: "BWK - White", value: "content/cabinets/bwk.md" },
  { label: "CSU - Saddle", value: "content/cabinets/csu.md" },
  { label: "CWU - Antique White", value: "content/cabinets/cwu.md" },
  { label: "ESCP - Grey Stain", value: "content/cabinets/escp.md" },
  { label: "ESGN - Grey", value: "content/cabinets/esgn.md" },
  { label: "ESN - White", value: "content/cabinets/esn.md" },
  { label: "ESNN - Blue", value: "content/cabinets/esnn.md" },
  { label: "ESOBN - Black", value: "content/cabinets/esobn.md" },
  { label: "ESOIN - Ivory", value: "content/cabinets/esoin.md" },
  { label: "ESOMN - Mocha", value: "content/cabinets/esomn.md" },
  { label: "ESON - Oak", value: "content/cabinets/eson.md" },
  { label: "FSH-IWB - Ivory White", value: "content/cabinets/fsh-iwb.md" },
  { label: "FSH-NBB - Navy Blue", value: "content/cabinets/fsh-nbb.md" },
  { label: "FSL-DGB - Dove Gray", value: "content/cabinets/fsl-dgb.md" },
  { label: "FSL-IWB - Ivory White", value: "content/cabinets/fsl-iwb.md" },
  { label: "FSL-NBB - Navy BLue", value: "content/cabinets/fsl-nbb.md" },
  { label: "HAAN - Ash", value: "content/cabinets/haan.md" },
  { label: "HABN - Blanco", value: "content/cabinets/habn.md" },
  { label: "HAWN - Walnut", value: "content/cabinets/hawn.md" },
  { label: "JGS - Green", value: "content/cabinets/jgs.md" },
  { label: "LSA - Light Grey", value: "content/cabinets/lsa.md" },
  { label: "LSE - Espresso Stain", value: "content/cabinets/lse.md" },
  { label: "LSG - Dark Grey", value: "content/cabinets/lsg.md" },
  { label: "LSKP - Light Brown Stain", value: "content/cabinets/lskp.md" },
  { label: "LSW - White", value: "content/cabinets/lsw.md" },
  { label: "MBS - Black", value: "content/cabinets/mbs.md" },
  { label: "MHWS - Off White Shaker", value: "content/cabinets/mhws.md" },
  { label: "MOSS - Moss Shaker", value: "content/cabinets/moss.md" },
  { label: "NWK - Napa White", value: "content/cabinets/nwk.md" },
  { label: "OMU - Light Grey Stain", value: "content/cabinets/omu.md" },
  { label: "OOK - Oak", value: "content/cabinets/ook.md" },
  { label: "OSN - Oak", value: "content/cabinets/osn.md" },
  { label: "OSU - Light Green", value: "content/cabinets/osu.md" },
  { label: "OTU - Light Brown Stain", value: "content/cabinets/otu.md" },
  { label: "OWK - White", value: "content/cabinets/owk.md" },
  { label: "OWU - White", value: "content/cabinets/owu.md" },
  { label: "PDM - Perfect Blue", value: "content/cabinets/pdm.md" },
  { label: "PRM - Perfect Brown", value: "content/cabinets/prm.md" },
  { label: "PSM - Perfect Sand", value: "content/cabinets/psm.md" },
  { label: "RHC - Clear Stain", value: "content/cabinets/rhc.md" },
  { label: "SBU - Shaker Black", value: "content/cabinets/sbu.md" },
  { label: "SCU - Shaker Cinder", value: "content/cabinets/scu.md" },
  { label: "SDU - Light Grey", value: "content/cabinets/sdu.md" },
  { label: "SDWA - White", value: "content/cabinets/sdwa.md" },
  { label: "SDWH - White Shaker", value: "content/cabinets/sdwh.md" },
  { label: "SEK - Espresso", value: "content/cabinets/sek.md" },
  { label: "SFB - White", value: "content/cabinets/sfb.md" },
  { label: "SGU - Shaker Grey", value: "content/cabinets/sgu.md" },
  { label: "SK - Mocha", value: "content/cabinets/sk.md" },
  { label: "SKK - Mocha", value: "content/cabinets/skk.md" },
  { label: "SMB - Mocha Stain", value: "content/cabinets/smb.md" },
  { label: "SNU - Shaker Navy", value: "content/cabinets/snu.md" },
  { label: "SSGH - Green", value: "content/cabinets/ssgh.md" },
  { label: "SSKP - Slim Shaker", value: "content/cabinets/sskp.md" },
  { label: "SWK - Designer White", value: "content/cabinets/swk.md" },
  { label: "SWOA - Light Brown Stain", value: "content/cabinets/swoa.md" },
  { label: "SWU - Shaker White", value: "content/cabinets/swu.md" },
  { label: "TGB - Green", value: "content/cabinets/tgb.md" },
  { label: "TGM - Mid Century Grey", value: "content/cabinets/tgm.md" },
  { label: "TWB - Off White", value: "content/cabinets/twb.md" },
  { label: "AB - Amber Shaker", value: "content/cabinets/ab.md" },
  { label: "AGA - Green", value: "content/cabinets/aga.md" },
  { label: "BOB - Beacon Oak", value: "content/cabinets/bob.md" },
  { label: "BSB - Beacon Shaker", value: "content/cabinets/bsb.md" },
  { label: "COB - Coyote Oak", value: "content/cabinets/cob.md" },
  { label: "CSB - Coyote Shaker", value: "content/cabinets/csb.md" },
  { label: "HAON - Havana White Oak", value: "content/cabinets/haon.md" },
  { label: "HSB - Haven Shaker", value: "content/cabinets/hsb.md" },
  { label: "IOB - Island Oak", value: "content/cabinets/iob.md" },
  { label: "LSBOP - Liberty Shaker Black", value: "content/cabinets/lsbop.md" },
  { label: "LSOP - Off White", value: "content/cabinets/lsop.md" },
  { label: "LSPP - Liberty Shaker Pine", value: "content/cabinets/lspp.md" },
  { label: "OCK - Oslo Classic Walnut", value: "content/cabinets/ock.md" },
  { label: "OOB - Oldstone Oak", value: "content/cabinets/oob.md" },
  { label: "OSBN - Black", value: "content/cabinets/osbn.md" },
  { label: "RWA - Rustic Wood", value: "content/cabinets/rwa.md" },
  { label: "SAOA - Amber Oak", value: "content/cabinets/saoa.md" },
  { label: "SAU - Off White", value: "content/cabinets/sau.md" },
  { label: "SHU - Light Brown", value: "content/cabinets/shu.md" },
  { label: "SIBA - Black", value: "content/cabinets/siba.md" },
  { label: "SIU - Green", value: "content/cabinets/siu.md" },
  { label: "STS - Taupe", value: "content/cabinets/sts.md" },
  { label: "WSB - Walnut Shaker", value: "content/cabinets/wsb.md" },
];

export const cabinetReferenceLabelsByValue: Record<string, string> = {
  "content/cabinets/aab.md": "AAB - Light Gray",
  "content/cabinets/aap.md": "AAP - Light Grey",
  "content/cabinets/abb.md": "ABB - Blue",
  "content/cabinets/acb.md": "ACB - Espresso Stain",
  "content/cabinets/aeb.md": "AEB - Black",
  "content/cabinets/algb.md": "ALGB - Artisanal Light Gray",
  "content/cabinets/anm.md": "ANM - New Grey Shaker",
  "content/cabinets/aop.md": "AOP - Off White",
  "content/cabinets/arm.md": "ARM - New Grey Shaker",
  "content/cabinets/atb.md": "ATB - Light Brown Stain",
  "content/cabinets/awb.md": "AWB - White",
  "content/cabinets/axm.md": "AXM - Extreme Blue Shaker",
  "content/cabinets/bfk.md": "BFK - Light Brown Stain",
  "content/cabinets/bgk.md": "BGK - Gray",
  "content/cabinets/bmk.md": "BMK - Blue",
  "content/cabinets/bsk.md": "BSK - Gray Stain",
  "content/cabinets/bwk.md": "BWK - White",
  "content/cabinets/csu.md": "CSU - Saddle",
  "content/cabinets/cwu.md": "CWU - Antique White",
  "content/cabinets/escp.md": "ESCP - Grey Stain",
  "content/cabinets/esgn.md": "ESGN - Grey",
  "content/cabinets/esn.md": "ESN - White",
  "content/cabinets/esnn.md": "ESNN - Blue",
  "content/cabinets/esobn.md": "ESOBN - Black",
  "content/cabinets/esoin.md": "ESOIN - Ivory",
  "content/cabinets/esomn.md": "ESOMN - Mocha",
  "content/cabinets/eson.md": "ESON - Oak",
  "content/cabinets/fsh-iwb.md": "FSH-IWB - Ivory White",
  "content/cabinets/fsh-nbb.md": "FSH-NBB - Navy Blue",
  "content/cabinets/fsl-dgb.md": "FSL-DGB - Dove Gray",
  "content/cabinets/fsl-iwb.md": "FSL-IWB - Ivory White",
  "content/cabinets/fsl-nbb.md": "FSL-NBB - Navy BLue",
  "content/cabinets/haan.md": "HAAN - Ash",
  "content/cabinets/habn.md": "HABN - Blanco",
  "content/cabinets/hawn.md": "HAWN - Walnut",
  "content/cabinets/jgs.md": "JGS - Green",
  "content/cabinets/lsa.md": "LSA - Light Grey",
  "content/cabinets/lse.md": "LSE - Espresso Stain",
  "content/cabinets/lsg.md": "LSG - Dark Grey",
  "content/cabinets/lskp.md": "LSKP - Light Brown Stain",
  "content/cabinets/lsw.md": "LSW - White",
  "content/cabinets/mbs.md": "MBS - Black",
  "content/cabinets/mhws.md": "MHWS - Off White Shaker",
  "content/cabinets/moss.md": "MOSS - Moss Shaker",
  "content/cabinets/nwk.md": "NWK - Napa White",
  "content/cabinets/omu.md": "OMU - Light Grey Stain",
  "content/cabinets/ook.md": "OOK - Oak",
  "content/cabinets/osn.md": "OSN - Oak",
  "content/cabinets/osu.md": "OSU - Light Green",
  "content/cabinets/otu.md": "OTU - Light Brown Stain",
  "content/cabinets/owk.md": "OWK - White",
  "content/cabinets/owu.md": "OWU - White",
  "content/cabinets/pdm.md": "PDM - Perfect Blue",
  "content/cabinets/prm.md": "PRM - Perfect Brown",
  "content/cabinets/psm.md": "PSM - Perfect Sand",
  "content/cabinets/rhc.md": "RHC - Clear Stain",
  "content/cabinets/sbu.md": "SBU - Shaker Black",
  "content/cabinets/scu.md": "SCU - Shaker Cinder",
  "content/cabinets/sdu.md": "SDU - Light Grey",
  "content/cabinets/sdwa.md": "SDWA - White",
  "content/cabinets/sdwh.md": "SDWH - White Shaker",
  "content/cabinets/sek.md": "SEK - Espresso",
  "content/cabinets/sfb.md": "SFB - White",
  "content/cabinets/sgu.md": "SGU - Shaker Grey",
  "content/cabinets/sk.md": "SK - Mocha",
  "content/cabinets/skk.md": "SKK - Mocha",
  "content/cabinets/smb.md": "SMB - Mocha Stain",
  "content/cabinets/snu.md": "SNU - Shaker Navy",
  "content/cabinets/ssgh.md": "SSGH - Green",
  "content/cabinets/sskp.md": "SSKP - Slim Shaker",
  "content/cabinets/swk.md": "SWK - Designer White",
  "content/cabinets/swoa.md": "SWOA - Light Brown Stain",
  "content/cabinets/swu.md": "SWU - Shaker White",
  "content/cabinets/tgb.md": "TGB - Green",
  "content/cabinets/tgm.md": "TGM - Mid Century Grey",
  "content/cabinets/twb.md": "TWB - Off White",
  "content/cabinets/ab.md": "AB - Amber Shaker",
  "content/cabinets/aga.md": "AGA - Green",
  "content/cabinets/bob.md": "BOB - Beacon Oak",
  "content/cabinets/bsb.md": "BSB - Beacon Shaker",
  "content/cabinets/cob.md": "COB - Coyote Oak",
  "content/cabinets/csb.md": "CSB - Coyote Shaker",
  "content/cabinets/haon.md": "HAON - Havana White Oak",
  "content/cabinets/hsb.md": "HSB - Haven Shaker",
  "content/cabinets/iob.md": "IOB - Island Oak",
  "content/cabinets/lsbop.md": "LSBOP - Liberty Shaker Black",
  "content/cabinets/lsop.md": "LSOP - Off White",
  "content/cabinets/lspp.md": "LSPP - Liberty Shaker Pine",
  "content/cabinets/ock.md": "OCK - Oslo Classic Walnut",
  "content/cabinets/oob.md": "OOB - Oldstone Oak",
  "content/cabinets/osbn.md": "OSBN - Black",
  "content/cabinets/rwa.md": "RWA - Rustic Wood",
  "content/cabinets/saoa.md": "SAOA - Amber Oak",
  "content/cabinets/sau.md": "SAU - Off White",
  "content/cabinets/shu.md": "SHU - Light Brown",
  "content/cabinets/siba.md": "SIBA - Black",
  "content/cabinets/siu.md": "SIU - Green",
  "content/cabinets/sts.md": "STS - Taupe",
  "content/cabinets/wsb.md": "WSB - Walnut Shaker",
};
