export type CabinetReferenceOption = {
  label: string;
  value: string;
};

export const cabinetReferenceSelectOptions: CabinetReferenceOption[] = [
  { label: "AAB - Artisanal Ash", value: "content/cabinets/aab.md" },
  { label: "AAP - Avalon Ashlen", value: "content/cabinets/aap.md" },
  { label: "ABB - Artisanal Blue", value: "content/cabinets/abb.md" },
  { label: "ACB - Artisanal Charcoal", value: "content/cabinets/acb.md" },
  { label: "AEB - Artisanal Ebony", value: "content/cabinets/aeb.md" },
  { label: "ALGB - Artisanal Light Gray", value: "content/cabinets/algb.md" },
  { label: "ANM - New Grey Shaker", value: "content/cabinets/anm.md" },
  { label: "AOP - Arlington Oatmeal", value: "content/cabinets/aop.md" },
  { label: "ARM - New Grey Shaker", value: "content/cabinets/arm.md" },
  { label: "ATB - Artisanal Timber", value: "content/cabinets/atb.md" },
  { label: "AWB - Artisanal White", value: "content/cabinets/awb.md" },
  { label: "AXM - Extreme Blue Shaker", value: "content/cabinets/axm.md" },
  { label: "BFK - Brooklyn Fawn", value: "content/cabinets/bfk.md" },
  { label: "BGK - Modern Gray", value: "content/cabinets/bgk.md" },
  { label: "BMK - Brooklyn Midnight", value: "content/cabinets/bmk.md" },
  { label: "BSK - Brooklyn Slate", value: "content/cabinets/bsk.md" },
  { label: "BWK - Brooklyn Bright White", value: "content/cabinets/bwk.md" },
  { label: "CSU - Saddle", value: "content/cabinets/csu.md" },
  { label: "CWU - Antique White", value: "content/cabinets/cwu.md" },
  { label: "ESCP - Essense Shaker Clemento", value: "content/cabinets/escp.md" },
  { label: "ESGN - Gray", value: "content/cabinets/esgn.md" },
  { label: "ESN - White", value: "content/cabinets/esn.md" },
  { label: "ESNN - Navy", value: "content/cabinets/esnn.md" },
  { label: "ESOBN - Black", value: "content/cabinets/esobn.md" },
  { label: "ESOIN - Ivory", value: "content/cabinets/esoin.md" },
  { label: "ESOMN - Mocha", value: "content/cabinets/esomn.md" },
  { label: "ESON - Oak", value: "content/cabinets/eson.md" },
  { label: "FSH-IWB - Ivory White", value: "content/cabinets/fsh-iwb.md" },
  { label: "FSH-NBB - Navy Blue", value: "content/cabinets/fsh-nbb.md" },
  { label: "FSL-DGB - Dove Gray", value: "content/cabinets/fsl-dgb.md" },
  { label: "FSL-IWB - Ivory White", value: "content/cabinets/fsl-iwb.md" },
  { label: "FSL-NBB - Navy BLue", value: "content/cabinets/fsl-nbb.md" },
  { label: "HAAN - Ash", value: "content/cabinets/haan.md" },
  { label: "HABN - Blanco", value: "content/cabinets/habn.md" },
  { label: "HAWN - Walnut", value: "content/cabinets/hawn.md" },
  { label: "JGS - Jade Green", value: "content/cabinets/jgs.md" },
  { label: "LSA - Liberty Shaker Ashen", value: "content/cabinets/lsa.md" },
  { label: "LSE - Liberty Shaker Espresso", value: "content/cabinets/lse.md" },
  { label: "LSG - Liberty Shaker Gray", value: "content/cabinets/lsg.md" },
  { label: "LSKP - Liberty Shaker Karmel", value: "content/cabinets/lskp.md" },
  { label: "LSW - Liberty Shaker White", value: "content/cabinets/lsw.md" },
  { label: "MBS - Milton Black", value: "content/cabinets/mbs.md" },
  { label: "MHWS - Off White Shaker", value: "content/cabinets/mhws.md" },
  { label: "MOSS - Moss Shaker", value: "content/cabinets/moss.md" },
  { label: "NWK - Napa White", value: "content/cabinets/nwk.md" },
  { label: "OMU - Oxford Mist", value: "content/cabinets/omu.md" },
  { label: "OOK - Slim Shaker White Oak", value: "content/cabinets/ook.md" },
  { label: "OSN - Oak", value: "content/cabinets/osn.md" },
  { label: "OSU - Oxford Sage", value: "content/cabinets/osu.md" },
  { label: "OTU - Oxford Toffee", value: "content/cabinets/otu.md" },
  { label: "OWK - Slim Shaker White", value: "content/cabinets/owk.md" },
  { label: "OWU - Oxford White", value: "content/cabinets/owu.md" },
  { label: "PDM - Perfect Blue", value: "content/cabinets/pdm.md" },
  { label: "PRM - Perfect Brown", value: "content/cabinets/prm.md" },
  { label: "PSM - Perfect Sand", value: "content/cabinets/psm.md" },
  { label: "RHC - Rustic Hickory", value: "content/cabinets/rhc.md" },
  { label: "SBU - Shaker Black", value: "content/cabinets/sbu.md" },
  { label: "SCU - Shaker Cinder", value: "content/cabinets/scu.md" },
  { label: "SDU - Shaker Dove", value: "content/cabinets/sdu.md" },
  { label: "SDWA - Slim Dove White", value: "content/cabinets/sdwa.md" },
  { label: "SDWH - White Shaker", value: "content/cabinets/sdwh.md" },
  { label: "SEK - Shaker Espresso", value: "content/cabinets/sek.md" },
  { label: "SFB - Slim Frost", value: "content/cabinets/sfb.md" },
  { label: "SGU - Shaker Grey", value: "content/cabinets/sgu.md" },
  { label: "SK - Sand Shaker", value: "content/cabinets/sk.md" },
  { label: "SKK - Shaker Kodiak", value: "content/cabinets/skk.md" },
  { label: "SMB - Slim Mocha", value: "content/cabinets/smb.md" },
  { label: "SNU - Shaker Navy", value: "content/cabinets/snu.md" },
  { label: "SSGH - Sage Green", value: "content/cabinets/ssgh.md" },
  { label: "SSKP - Slim Shaker", value: "content/cabinets/sskp.md" },
  { label: "SWK - Designer White", value: "content/cabinets/swk.md" },
  { label: "SWOA - Slim White Oak", value: "content/cabinets/swoa.md" },
  { label: "SWU - Shaker White", value: "content/cabinets/swu.md" },
  { label: "TGB - Trenton Fairy", value: "content/cabinets/tgb.md" },
  { label: "TGM - Mid Century Grey", value: "content/cabinets/tgm.md" },
  { label: "TWB - Trenton Swan White", value: "content/cabinets/twb.md" },
];

export const cabinetReferenceLabelsByValue: Record<string, string> = {
  "content/cabinets/aab.md": "AAB - Artisanal Ash",
  "content/cabinets/aap.md": "AAP - Avalon Ashlen",
  "content/cabinets/abb.md": "ABB - Artisanal Blue",
  "content/cabinets/acb.md": "ACB - Artisanal Charcoal",
  "content/cabinets/aeb.md": "AEB - Artisanal Ebony",
  "content/cabinets/algb.md": "ALGB - Artisanal Light Gray",
  "content/cabinets/anm.md": "ANM - New Grey Shaker",
  "content/cabinets/aop.md": "AOP - Arlington Oatmeal",
  "content/cabinets/arm.md": "ARM - New Grey Shaker",
  "content/cabinets/atb.md": "ATB - Artisanal Timber",
  "content/cabinets/awb.md": "AWB - Artisanal White",
  "content/cabinets/axm.md": "AXM - Extreme Blue Shaker",
  "content/cabinets/bfk.md": "BFK - Brooklyn Fawn",
  "content/cabinets/bgk.md": "BGK - Modern Gray",
  "content/cabinets/bmk.md": "BMK - Brooklyn Midnight",
  "content/cabinets/bsk.md": "BSK - Brooklyn Slate",
  "content/cabinets/bwk.md": "BWK - Brooklyn Bright White",
  "content/cabinets/csu.md": "CSU - Saddle",
  "content/cabinets/cwu.md": "CWU - Antique White",
  "content/cabinets/escp.md": "ESCP - Essense Shaker Clemento",
  "content/cabinets/esgn.md": "ESGN - Gray",
  "content/cabinets/esn.md": "ESN - White",
  "content/cabinets/esnn.md": "ESNN - Navy",
  "content/cabinets/esobn.md": "ESOBN - Black",
  "content/cabinets/esoin.md": "ESOIN - Ivory",
  "content/cabinets/esomn.md": "ESOMN - Mocha",
  "content/cabinets/eson.md": "ESON - Oak",
  "content/cabinets/fsh-iwb.md": "FSH-IWB - Ivory White",
  "content/cabinets/fsh-nbb.md": "FSH-NBB - Navy Blue",
  "content/cabinets/fsl-dgb.md": "FSL-DGB - Dove Gray",
  "content/cabinets/fsl-iwb.md": "FSL-IWB - Ivory White",
  "content/cabinets/fsl-nbb.md": "FSL-NBB - Navy BLue",
  "content/cabinets/haan.md": "HAAN - Ash",
  "content/cabinets/habn.md": "HABN - Blanco",
  "content/cabinets/hawn.md": "HAWN - Walnut",
  "content/cabinets/jgs.md": "JGS - Jade Green",
  "content/cabinets/lsa.md": "LSA - Liberty Shaker Ashen",
  "content/cabinets/lse.md": "LSE - Liberty Shaker Espresso",
  "content/cabinets/lsg.md": "LSG - Liberty Shaker Gray",
  "content/cabinets/lskp.md": "LSKP - Liberty Shaker Karmel",
  "content/cabinets/lsw.md": "LSW - Liberty Shaker White",
  "content/cabinets/mbs.md": "MBS - Milton Black",
  "content/cabinets/mhws.md": "MHWS - Off White Shaker",
  "content/cabinets/moss.md": "MOSS - Moss Shaker",
  "content/cabinets/nwk.md": "NWK - Napa White",
  "content/cabinets/omu.md": "OMU - Oxford Mist",
  "content/cabinets/ook.md": "OOK - Slim Shaker White Oak",
  "content/cabinets/osn.md": "OSN - Oak",
  "content/cabinets/osu.md": "OSU - Oxford Sage",
  "content/cabinets/otu.md": "OTU - Oxford Toffee",
  "content/cabinets/owk.md": "OWK - Slim Shaker White",
  "content/cabinets/owu.md": "OWU - Oxford White",
  "content/cabinets/pdm.md": "PDM - Perfect Blue",
  "content/cabinets/prm.md": "PRM - Perfect Brown",
  "content/cabinets/psm.md": "PSM - Perfect Sand",
  "content/cabinets/rhc.md": "RHC - Rustic Hickory",
  "content/cabinets/sbu.md": "SBU - Shaker Black",
  "content/cabinets/scu.md": "SCU - Shaker Cinder",
  "content/cabinets/sdu.md": "SDU - Shaker Dove",
  "content/cabinets/sdwa.md": "SDWA - Slim Dove White",
  "content/cabinets/sdwh.md": "SDWH - White Shaker",
  "content/cabinets/sek.md": "SEK - Shaker Espresso",
  "content/cabinets/sfb.md": "SFB - Slim Frost",
  "content/cabinets/sgu.md": "SGU - Shaker Grey",
  "content/cabinets/sk.md": "SK - Sand Shaker",
  "content/cabinets/skk.md": "SKK - Shaker Kodiak",
  "content/cabinets/smb.md": "SMB - Slim Mocha",
  "content/cabinets/snu.md": "SNU - Shaker Navy",
  "content/cabinets/ssgh.md": "SSGH - Sage Green",
  "content/cabinets/sskp.md": "SSKP - Slim Shaker",
  "content/cabinets/swk.md": "SWK - Designer White",
  "content/cabinets/swoa.md": "SWOA - Slim White Oak",
  "content/cabinets/swu.md": "SWU - Shaker White",
  "content/cabinets/tgb.md": "TGB - Trenton Fairy",
  "content/cabinets/tgm.md": "TGM - Mid Century Grey",
  "content/cabinets/twb.md": "TWB - Trenton Swan White",
};
