import HeroBlock from "./HeroBlock";
import ProductsSectionBlock from "./ProductsSectionBlock";
import ServicesSectionBlock from "./ServicesSectionBlock";
import ProjectsSectionBlock from "./ProjectsSectionBlock";
import WhyUsSectionBlock from "./WhyUsSectionBlock";
import AboutSectionBlock from "./AboutSectionBlock";
import ShowroomBannerBlock from "./ShowroomBannerBlock";
import ProcessSectionBlock from "./ProcessSectionBlock";
import FAQSectionBlock from "./FAQSectionBlock";
import ContactSectionBlock from "./ContactSectionBlock";
import RichContentBlock from "./RichContentBlock";

// Map __typename (generated by TinaCMS) to components.
// Pattern: {CollectionName}Blocks{TemplateName}
const BLOCK_MAP: Record<string, React.ComponentType<{ block: any }>> = {
  // Page collection blocks
  PageBlocksHero: HeroBlock,
  PageBlocksProductsSection: ProductsSectionBlock,
  PageBlocksServicesSection: ServicesSectionBlock,
  PageBlocksProjectsSection: ProjectsSectionBlock,
  PageBlocksWhyUsSection: WhyUsSectionBlock,
  PageBlocksAboutSection: AboutSectionBlock,
  PageBlocksShowroomBanner: ShowroomBannerBlock,
  PageBlocksProcessSection: ProcessSectionBlock,
  PageBlocksFaqSection: FAQSectionBlock,
  PageBlocksContactSection: ContactSectionBlock,
  PageBlocksRichContent: RichContentBlock,

  // Service collection blocks
  ServiceBlocksHero: HeroBlock,
  ServiceBlocksFeatures: WhyUsSectionBlock,
  ServiceBlocksCtaBanner: ShowroomBannerBlock,
};

export default function BlockRenderer({ blocks }: { blocks: any[] }) {
  if (!blocks?.length) return null;
  return (
    <>
      {blocks.map((block, i) => {
        const Component = BLOCK_MAP[block.__typename];
        if (!Component) {
          console.warn(`No component found for block type: ${block.__typename}`);
          return null;
        }
        return <Component key={i} block={block} />;
      })}
    </>
  );
}
